on: push

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: shirok/setup-gauche@v3
          with:
            gauche-version: '0.9.15'
        - run: (cd test && gosh factorial.scm)
